logspout:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
  command:
  - syslog://${syslog}
  image: registry.cntv.net/logspout:v2
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock
  stdin_open: true


