.catalog:
  name: "Kong"
  version: "v1-postgres:9.4"
  description: "kong use postgres"
  questions:
    - variable: "REPLICAS"
      description: "Number of Kong"
      label: "Number of Nodes:"
      required: true
      default: 3
      type: "int"
  kong:
   retain_ip: true
   scale: ${REPLICAS}  
  kong-database:
   scale: 1
