glusterfs-server:
  image: registry.cntv.net/rancher/glusterfs:v0.1.3
  cap_add:
    - SYS_ADMIN
  volumes_from:
    - glusterfs-data
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: glusterfs-peer,glusterfs-data,glusterfs-volume-create
  command: "glusterd -p /var/run/gluster.pid -N"
glusterfs-peer:
  image: registry.cntv.net/rancher/glusterfs:v0.1.3
  net: 'container:glusterfs-server'
  volumes_from:
    - glusterfs-data
  labels:
    io.rancher.container.hostname_override: container_name
  command: /opt/rancher/peerprobe.sh
glusterfs-data:
  image: registry.cntv.net/rancher/glusterfs:v0.1.3
  command: /bin/true
  volumes:
    - /var/run
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
glusterfs-volume-create:
  image: registry.cntv.net/rancher/glusterfs:v0.1.3
  command: /opt/rancher/replicated_volume_create.sh
  net: 'container:glusterfs-server'
  volumes_from:
    - glusterfs-data
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
